### ISSUE TITLE
The containers are restarting continuously.

### ISSUE THREAD

**Issue by pascalandy** [jwasham/docker-ghost-template#1]
Hey John,

I got an issue here. The containers are restarting continuously. It does this behavior locally (via virtualbox) and remotely on DigitalOcean. The main page is never loading and all connexion are refused. 

Here is a screen shot where I do a couple of docker ps in a row:

![screenr 2016-02-23 at 10 17 12 pm](https://cloud.githubusercontent.com/assets/6694151/13274721/7beae40e-da7b-11e5-8819-190252ce8a35.jpg)

**Comment by jwasham** [comment]
Hi there,
Thanks for using my github project.
Check the docker logs to see what is happening internally:
Usage: docker logs [OPTIONS] CONTAINER

**Comment by pascalandy** [comment]
Good point! I clearly have an issue with the SSL certificates. 

I went into nginx/volumes/ssl/ and ran: 
`sudo openssl req -x509 -nodes -newkey rsa:2048 -keyout nginx.key -out nginx.crt` to generate my keys.

It is still not working here :angry: but I'll follow up :+1:

**Comment by jwasham** [comment]
OK, let me know. I'm letting NGINX terminate SSL so Ghost doesn't have to handle it. I'm running my blog on this container set, and have only made changes to the template for Disqus and some styles. Other than that (and the settings you override in docker-compose.yml) it's working out of the box.

**Comment by jwasham** [comment]
Let me know how it's going for you, and I'll close this issue.

**Comment by pascalandy** [comment]
John,

Could you point me to some docs about setting this? I followed the instruction from https://www.youtube.com/watch?v=D2P5cRMi0fQ and I'm still blocked with the SSL part of the setup.

Cheers!

**Comment by jwasham** [comment]
The full instructions for setting up the system are here: https://github.com/jwasham/docker-ghost-template

For the SSL portion, you only need to add your SSL certificate and key to nginx/volumes/ssl/ (there are placeholders there). The ssl directory will get mounted into the container when the container starts.

**Comment by pascalandy** [comment]
I confirm it's all working now :)
