### ISSUE TITLE
S3 configuration

### ISSUE THREAD

**Issue by pascalandy** [jwasham/docker-ghost-template#3]
Hey John,

I don't want to abuse your time but maybe you can give me your cue. Have an issue where I can upload a picture via Ghost, see in in AWS S3 but Ghost is not seeing the picture and the cute giffy cat stays there for ever. Here is a screen cast (56 sec) about the setup http://jmp.sh/uyhocJC.

Could you point me to some docs about all the steps to configure AWS?

For anyone who would like to help, I created an official job for this - https://github.com/pascalandy/pair_programming_35tg2/tree/master/pair_programming_04

Thank you!

**Comment by jwasham** [comment]
From your screenshare it looks like you have S3 and IAM set up fine. What you are missing is the Cloudfront portion for serving the images through a CDN (since S3 is slow as a server). I can walk you through that. I'm on Telegram now. I guess you can find me by name, right?

**Comment by pascalandy** [comment]
I'll buzz you in about 1h :)

**Comment by jwasham** [comment]
Was good talking with you!
