### ISSUE TITLE
s3 plugin is broken since 0.10.0

### ISSUE THREAD

**Issue by pascalandy** [jwasham/docker-ghost-template#4]
Hey John,

Since Ghost 0.10.0 the [actual s3 plugin](https://github.com/muzix/ghost-s3/issues/21) does not work anymore :( This [is well documented ](https://github.com/TryGhost/Ghost/wiki/Using-a-custom-storage-module#creating-a-module)by the Ghost team.

The good news is that [other plugins that are supported](). Those two looks solid:
- https://github.com/spanishdict/ghost-s3-compat
- https://github.com/colinmeinke/ghost-storage-adapter-s3

Would be awesome to update this project, so we can update to Ghost 0.11 LTS. I'm still clueless about the way you inject the plug-in from the official image LOL.

Many, many thanks once again !

Cheers!
Pascal

**Comment by jwasham** [comment]
It's something I want to update and will do it soon. Thanks!

**Comment by jwasham** [comment]
I updated the project to Ghost version 0.11.0 and added upgrade instructions to README.md.
Enjoy!
